import type { Metadata } from "next";
import "./globals.css";

import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Welcome to Digicart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <Header />
        <div className="flex flex-1">
          <Sidebar />

          <main className="flex-1 bg-gray-50 p-4 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
